#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -eo pipefail

inputs=(ci tools)

echo "Running shellcheck..."

find "${inputs[@]/#/$1}" -type f \( -executable -or -name '*.sh' \) -print0 |\
    xargs -0 shellcheck -e SC1071 --severity=warning
