#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -eo pipefail

inputs=(setup.py.in src tests examples)

echo "Running black..."

if [[ $1 == --dry-run ]]; then
    opts="--check"

    shift
fi

black $opts "${inputs[@]/#/$1}"
