# Reference https://github.com/facebookresearch/fairseq2/blob/v0.5.0a1/src/fairseq2/recipe/config.py#L41 for the correct syntax.
model:
  arch: "large"
  config_overrides:
    encoder_config:
      first_pass_dropout_p: 0.1


dataset:
  max_audio_len: 320_000
  max_num_elements: 1_200_000

optimizer:
  config:
    lr: 3e-04

lr_scheduler:
  config:
    num_warmup_steps: 20_000

regime:
  num_steps: 250_000
  publish_metrics_every_n_steps: 100
