# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

FROM ghcr.io/facebookresearch/fairseq2-ci-manylinux_x86_64:1-cu118

COPY build-scripts/install-llvm.sh /build-scripts/

RUN /build-scripts/install-llvm.sh && rm -rf /build-scripts
