# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

dataset:
  valid_split: null
  train_split: "sft"
  batch_size: 16
  chat_mode: false
  config_overrides:
    path: "/checkpoint/ram/jacklanchantin/data/gsm8k_sft/"
  family: "llama"
  name: "llama3_2_1b"
tokenizer:
  family: "llama"
  name: "llama3_2_1b"
common:
  metric_recorders:
    wandb:
      enabled: True
      project: "fairseq2"
      run_name: "test_llama3_2_1b_sft_gsm8k"
regime:
  num_steps: 100000
  checkpoint_every_n_steps: 100
  validate_every_n_steps: 100
  checkpoint_every_n_data_epochs: 100
  keep_last_n_checkpoints: 10
  publish_metrics_every_n_steps: 1
  save_model_only: false