# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

dataset:
  _set_:
    valid_split: "valid"
    batch_size: 16
    chat_mode: false
    config_overrides:
      path: "/checkpoint/ram/jacklanchantin/data/alpaca/"
model:
  _set_:
    family: "llama"
    name: "llama3_2_1b"
tokenizer:
  _set_:
    family: "llama"
    name: "llama3_2_1b"
common:
  metric_recorders:
    wandb:
      enabled: True
      project: "fairseq2"
      run_name: "test_llama3_2_1b_sft_alpaca"
regime:
  _set_:
    num_steps: 48000
    checkpoint_every_n_steps: 100
    validate_every_n_steps: 100
    checkpoint_every_n_data_epochs: 100
    keep_last_n_checkpoints: 10
    publish_metrics_every_n_steps: 1
    save_model_only: false