# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

dataset:
  valid_split: "test_qwen"
  train_split: "train_qwen"
  batch_size: 16
  chat_mode: false
  config_overrides:
    path: "/checkpoint/ram/jacklanchantin/data/gsm8k_sft"
model:
  family: "qwen"
  name: "qwen3_4b"
tokenizer:
  name: "qwen3_4b"
common:
  metric_recorders:
    wandb:
      enabled: True
      project: "fairseq2"
      run_name: "sft_qwen3_4b_chat_gsm8k"
regime:
  num_steps: 100000
  checkpoint_every_n_steps: 100
  validate_every_n_steps: 100
  checkpoint_every_n_data_epochs: 100
  keep_last_n_checkpoints: 10
  publish_metrics_every_n_steps: 1
  save_model_only: false
