# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# matching configuration to large_960h.yaml

model:
  arch: "large"
  config_overrides:
    encoder_config:
      first_pass_dropout_p: 0.1

dataset:
  max_audio_len: 320_000
  max_num_elements: 1_200_000

dataset:
  name: "librispeech_960h"
  valid_split: "valid" # multiple splits supported ("valid,test-clean")

evaluator:
  dtype: "torch.float16"

loss:
  diversity_loss_weight: 0.1
  feature_penalty_weight: 10.0
