#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -eo pipefail

function print_usage
{
    echo "Usage: run-clang-format [--dry-run] TARGETS"
}

function exit_with_usage
{
    print_usage >&1

    exit 0
}

function exit_with_error
{
    print_usage >&2

    exit 1
}

function main() {
    if [[ $# -eq 0 ]]; then
        exit_with_error
    fi

    TARGETS=()
    quiet=0
    dry_run=0
    for x in "$@"; do
  case "$x" in
    '--dry-run')
      dry_run=1
      ;;

    '-q')
      quiet=1
      ;;

    '-'*)
      exit_with_error
      ;;

    *)
      TARGETS+=( "$x" )
      ;;
  esac
done


  if (( $dry_run )); then
      opts="--Werror --dry-run"
  else
      opts="-i"
  fi
  if (( ! $quiet )); then
      opts="$opts --verbose"
  fi

  find "${TARGETS[@]}" \
      \( -type d \( -name '.?*' -or -name 'build' -or -name 'third-party' \) -prune \) -or \
      \( -type f \( -name '*.cc' -or -name '*.cu' -or -name '*.h' \) -print0 \) \
      | xargs -0 clang-format $opts

}

main "$@"