#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

function run_python_linters
{
    echo "Running flake8..."
    flake8 "$@"

    echo "Running isort..."
    isort "$@"

    echo "Running black..."
    black "$@"

    echo "Running mypy..."
    mypy --pretty --show-error-codes "$@"
}

function run_script_linters
{
    echo "Running shellcheck..."
    shellcheck "$@"
}

run_python_linters setup.py fairseq2 tests examples

run_script_linters scripts/*
