#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

function print_usage
{
    printf "Usage: %s PEP440_VERSION\n" "$(basename "$0")"
}

function replace_match
{
    sed --in-place --expression "$2" "$1"
}

if [[ $# -ne 1 ]]; then
    print_usage >&2 && exit 1
fi

if [[ $1 == -h || $1 == --help ]]; then
    print_usage >&2 && exit 0
fi

cd "$(dirname "$0")"/..

# Update the package.
replace_match fairseq2/__init__.py "s/__version__ = \".*\"/__version__ = \"$1\"/"

# Update the distribution.
replace_match setup.py "s/version=\".*\"/version=\"$1\"/"

# Update the VERSION file.
echo "$1" > VERSION
