# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

model:
  arch: "base_10h"
  family: "wav2vec2_asr"

pretrained_model:
  name: "wav2vec2_base"

dataset:
  name: "librilight_asr_10h"
  train_split: "train"
  valid_split: "dev_other"
  max_audio_len: 800_000
  max_num_elements: 3_200_000

tokenizer:
  name: "librispeech_asr"

optimizer:
  config:
    lr: 5e-05

trainer:
  mixed_precision:
    dtype: "torch.float16"
  freeze_encoder_for_n_steps: 10_000
  grad_accumulation:
    num_batches: 4

regime:
  num_steps: 20_000
  validate_after_n_steps: 10_000
  validate_every_n_steps: 1_000
  publish_metrics_every_n_steps: 200
  checkpoint_every_n_steps: 1_000
