# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

model:
  arch: "large_10h"

pretrained_model:
  name: "wav2vec2_large"

dataset:
  name: "librilight_asr_10h"
  train_split: "train"
  valid_split: "dev_other"
  max_audio_len: 640_000
  max_num_elements: 1_280_000

tokenizer:
  name: "librispeech_asr"

optimizer:
  config:
    lr: 1e-04

trainer:
  dtype: "torch.float16"
  freeze_encoder_for_n_steps: 10_000
  grad_accumulation:
    num_batches: 5 # needs to be in sync with dataset.num_accumulate

regime:
  num_steps: 20_000
  validate_after_n_steps: 9999
  validate_every_n_steps: 1_000
  publish_metrics_every_n_steps: 200
