#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

base_dir=$(cd "$(dirname "$0")" && pwd)/..


function run_clang_format
{
    echo "Running clang-format..."

    find "$@" \( -name '*.cc' -or -name '*.h' \) -type f -exec clang-format -i '{}' \+
}

function main
{
    run_clang_format "${@/#/$base_dir/}"
}

main src tests examples
