#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -eo pipefail

if [[ $# -ne 0 ]]; then
    echo "Usage: format-cc" >&2

    exit 1
fi

tools_dir=$(cd "$(dirname "$0")" && pwd)

"$tools_dir/porcelain/run-clang-format" "$tools_dir/../"
