#!/bin/bash

# Exit on error.
set -e
set -eo pipefail

# Standard trick to resolve the 'real' location of
# the directory this file is run from; and the workspace from that.
WORKSPACE_ROOT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd)"
cd $WORKSPACE_ROOT_DIR || exit 1

isort .

black .

tools/linters/run-clang-format .

