#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

base_dir=$(cd "$(dirname "$0")" && pwd)/..


function run_shellcheck
{
    echo "Running shellcheck..."

    find "$@" -type f -exec shellcheck '{}' \;
}

function main
{
    run_shellcheck "${@/#/$base_dir/}"
}

main tools
