#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

base_dir=$(cd "$(dirname "$0")" && pwd)/..


function main
{
    set -- "${@/#/$base_dir/}"

    echo "Running flake8..."

    flake8 "$@"

    echo "Running mypy..."

    mypy --pretty "$@"
}

main setup.py.in src tests examples
