#!/bin/bash

# Exit on error.
set -eo pipefail

# Standard trick to resolve the 'real' location of
# the directory this file is run from; and the workspace from that.
WORKSPACE_ROOT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd)"
cd $WORKSPACE_ROOT_DIR || exit 1

echo "Formatting Code"
tools/format

echo "Running Lint"
tools/lint

echo "Rebuilding Plugins"
if ! cmake --build build; then
  tools/recreate-build;
  cmake --build build;
fi

echo "Running Tests"
pytest tests

echo "Presubmit: Success"
