#!/bin/bash

# Exit on error.
set -ex
set -eo pipefail

# Standard trick to resolve the 'real' location of
# the directory this file is run from; and the workspace from that.
WORKSPACE_ROOT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd)"
cd $WORKSPACE_ROOT_DIR || exit 1

if [ ! -f setup.cfg ]; then
  echo "Running outside workspace root: $PWD"
  exit 1
fi

echo "Initializing submodules"
git submodule update --init --recursive

echo "Recreating virtualenv: $PWD/.venv"
rm -rf .venv
python -m venv .venv

echo "Activating virtualenv: source $PWD/.venv/bin/activate"
source .venv/bin/activate

# PIP constraints, .gitignore'd local config file.
# Useful for directing pytorch/CUDA version.
#
# Example:
# --extra-index-url https://download.pytorch.org/whl/cu116
PIP_OPTS_FILE=devel-pip.opts
PIP_OPTS=
if [ -f $PIP_OPTS_FILE ]; then
  echo "Including local pip constraints: $PWD/$PIP_OPTS_FILE"
  PIP_OPTS="-c $PIP_OPTS_FILE"
else
  echo "No local pip constraints found: $PWD/$PIP_OPTS_FILE"
fi

echo "Installing torch first, to force CUDA version"
pip install $PIP_OPTS torch

echo "Installing requirements"
pip install $PIP_OPTS -r requirements-devel.txt

echo "Self-installing editable package"
pip install $PIP_OPTS -e .

tools/recreate-build

echo "CMake Build"
cmake --build build

