#!/usr/bin/env bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set -o errexit

curl --location --fail --output awscli.zip\
    https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.8.3.zip

unzip awscli.zip

aws/install --bin-dir /usr/bin

rm -rf aws awscli.zip
