#!/usr/bin/env bash

set -o errexit

git clone --depth 1 --recurse-submodules --shallow-submodules --branch llvmorg-13.0.1\
    https://github.com/llvm/llvm-project.git /root/llvm

cmake -GNinja\
      -S /root/llvm/llvm\
      -B /root/llvm-build\
      -DCMAKE_BUILD_TYPE=Release\
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;openmp"\
      -DLLVM_TARGETS_TO_BUILD=host\
      -Wno-dev

cmake --build /root/llvm-build && cmake --install /root/llvm-build

rm -rf /root/llvm
rm -rf /root/llvm-build
