# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Nightly

on:
  # At 1:15AM UTC on every Monday.
  schedule:
    - cron: '15 1 * * 1'

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      release_type: 'nightly'
